version: "3.9"

services:
    baistro:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        env_file:
            - ./.env
        stop_signal: SIGINT
        environment:
            PORT: 80
            SERVICE_NAME: baistro
            SERVICE_NAMESPACE: bai
        volumes:
            # note: only use the cache mounts for the `dev` image
            - baistro_0_poetry:/root/.cache/pypoetry
            - baistro_0_pip:/root/.cache/pip
            - ./baistro:/app/baistro
            - ./model-assets:/app/model-assets
            - ./pyproject.toml:/app/pyproject.toml
            - ./poetry.lock:/app/poetry.lock
        ports:
            - "8702:80"

volumes:
    baistro_0_poetry:
    baistro_0_pip:
